### PR TITLE
python/its-status: new client, to publish ITS status messages

### PR DESCRIPTION
**Pull request by ymorin-orange**
**New features:**
* `its-status`: new python client to publish ITS status messages that match the status schema

---
**How to test:**

1. build and install `python/its-status` with standard setuptools procedure;
2. create a configuration file, using `its-status.cfg` as startup point, adapt with your MQTT broker and credentials, enable the `stdout` emitter;
3. subscribe an MQTT client to your broker, on the status topic, e.g. with mosquitto CLI clients:
    ```sh
    $ mosquitto_sub -h BROKER -p PORT -u USERNAME -P PASSWORD -i ID -t 'status/#'
    ```
4. run `its-status` using your custom configuration file:
    ```sh
    $ its-status -c /path/to/its-status.custom.cfg
    ```

---
**Expected results:**

1. The `its-status` package is installed;
2. You have a custom configuration file with your MQTT settings;
3. The MQTT client is connected to your MQTT broker;
4. The `its-status` program runs, and the messages are visible both on the `its-status`' own `stdout`, as well as on the MQTT client.

### CODE REVIEW

**Comment by ymorin-orange** [comment]
@tigroo There is an issue on the rpi2 while collecting the celullar modem data.  
Investigations in progress.

If that does bear fruits by tomorrow, I'll de-priorise the rpi2 for now...

**Comment by ymorin-orange** [comment]
@tigroo @nbuffon This is ready for review now.

**Comment by tigroo** [comment]
Add a short sentence about its-status into the root Readme.md would be great

**Comment by tigroo** [comment]
Add a short Readme.md with great links on "how to use setup.py" would be great. otherwise, for me for example now, I don't see how to run its-status  :(.

**Comment by tigroo** [comment]
we must remove all the comment into the template config file to avoid a crash:

```
(its-client) kvmk8371@yd-5cd9245wbl:/workspace/project/its-client$ /home/kvmk8371/.local/bin/its-status --config /home/kvmk8371/.local/bin/its-status.cfg 
Exception in thread gpsd_client:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kvmk8371/.local/lib/python3.10/site-packages/its_status/collector.gnss.py", line 55, in __loop
    self.__connect()
  File "/home/kvmk8371/.local/lib/python3.10/site-packages/its_status/collector.gnss.py", line 40, in __connect
    self.sock.connect((self.cfg["host"], int(self.cfg["port"])))
ValueError: invalid literal for int() with base 10: '2947  # the port gpsd listens on'
Traceback (most recent call last):
  File "/home/kvmk8371/.local/bin/its-status", line 8, in <module>
    sys.exit(main())
  File "/home/kvmk8371/.local/lib/python3.10/site-packages/its_status/main.py", line 28, in main
    its_status.init(cfg=cfg)
  File "/home/kvmk8371/.local/lib/python3.10/site-packages/its_status/__init__.py", line 55, in init
    "obj": mod.Status(*args, **kwargs),
  File "/home/kvmk8371/.local/lib/python3.10/site-packages/its_status/emitter.stdout.py", line 11, in __init__
    self.enabled = cfg.getboolean("stdout", "enabled", fallback=False)
  File "/usr/lib/python3.10/configparser.py", line 829, in getboolean
    return self._get_conv(section, option, self._convert_to_boolean,
  File "/usr/lib/python3.10/configparser.py", line 809, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "/usr/lib/python3.10/configparser.py", line 804, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.10/configparser.py", line 1167, in _convert_to_boolean
    raise ValueError('Not a boolean: %s' % value)
ValueError: Not a boolean: true  # or false, the default
```
It would be great to move the comment on an above new independent line, to keep it without perturbate the config file parser.

**Comment by tigroo** [comment]
build ok:

```
/home/kvmk8371/.local/share/virtualenvs/its-client-BRfZhz36/bin/python /workspace/project/its-client/python/its-status/setup.py bdist_wheel 
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/its_status
copying its_status/collector.static.py -> build/lib/its_status
copying its_status/helpers.py -> build/lib/its_status
copying its_status/emitter.stdout.py -> build/lib/its_status
copying its_status/collector.gnss.py -> build/lib/its_status
copying its_status/collector.time_sources.py -> build/lib/its_status
copying its_status/main.py -> build/lib/its_status
copying its_status/__init__.py -> build/lib/its_status
copying its_status/collector.cellular.py -> build/lib/its_status
copying its_status/collector.system.py -> build/lib/its_status
copying its_status/emitter.mqtt.py -> build/lib/its_status
running egg_info
writing its_status.egg-info/PKG-INFO
writing dependency_links to its_status.egg-info/dependency_links.txt
writing entry points to its_status.egg-info/entry_points.txt
writing requirements to its_status.egg-info/requires.txt
writing top-level names to its_status.egg-info/top_level.txt
reading manifest file 'its_status.egg-info/SOURCES.txt'
writing manifest file 'its_status.egg-info/SOURCES.txt'
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/its_status
copying build/lib/its_status/collector.static.py -> build/bdist.linux-x86_64/wheel/its_status
copying build/lib/its_status/helpers.py -> build/bdist.linux-x86_64/wheel/its_status
copying build/lib/its_status/emitter.stdout.py -> build/bdist.linux-x86_64/wheel/its_status
copying build/lib/its_status/collector.gnss.py -> build/bdist.linux-x86_64/wheel/its_status
copying build/lib/its_status/collector.time_sources.py -> build/bdist.linux-x86_64/wheel/its_status
copying build/lib/its_status/main.py -> build/bdist.linux-x86_64/wheel/its_status
copying build/lib/its_status/__init__.py -> build/bdist.linux-x86_64/wheel/its_status
copying build/lib/its_status/collector.cellular.py -> build/bdist.linux-x86_64/wheel/its_status
copying build/lib/its_status/collector.system.py -> build/bdist.linux-x86_64/wheel/its_status
copying build/lib/its_status/emitter.mqtt.py -> build/bdist.linux-x86_64/wheel/its_status
running install_egg_info
Copying its_status.egg-info to build/bdist.linux-x86_64/wheel/its_status-0.0.0-py3.10.egg-info
running install_scripts
/home/kvmk8371/.local/share/virtualenvs/its-client-BRfZhz36/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
creating build/bdist.linux-x86_64/wheel/its_status-0.0.0.dist-info/WHEEL
creating 'dist/its_status-0.0.0-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'its_status/__init__.py'
adding 'its_status/collector.cellular.py'
adding 'its_status/collector.gnss.py'
adding 'its_status/collector.static.py'
adding 'its_status/collector.system.py'
adding 'its_status/collector.time_sources.py'
adding 'its_status/emitter.mqtt.py'
adding 'its_status/emitter.stdout.py'
adding 'its_status/helpers.py'
adding 'its_status/main.py'
adding 'its_status-0.0.0.dist-info/METADATA'
adding 'its_status-0.0.0.dist-info/WHEEL'
adding 'its_status-0.0.0.dist-info/entry_points.txt'
adding 'its_status-0.0.0.dist-info/top_level.txt'
adding 'its_status-0.0.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel

Process finished with exit code 0
```

**Pull request merged**
