### PR TITLE
python: shuffle its-client one directory down

### PR DESCRIPTION
**Pull request by ymorin-orange**
Prepare directory structure to receive additional python clients.  
No functional change, just directory layout shuffling.

---
**How to test:**

1. The python-related workflows still work:
    * python_its-client.yml => Python its-client
    * docker.yml => Run the its client container => Run Python docker action

### CODE REVIEW

**Comment by ymorin-orange** [comment]
@tigroo Sorry for the messy switch back and forth between Ready<->Draft.  
I'm still learing this Github mess...

**Review by tigroo — CHANGES_REQUESTED** [review]
Hum, somthing is strange :
```
$ ls -l python/
total 28
drwxrwxr-x 4 kvmk8371 kvmk8371 4096 gen.  25  2022 build
drwxrwxr-x 2 kvmk8371 kvmk8371 4096 abr.  15 16:21 dist
drwxrwxr-x 3 kvmk8371 kvmk8371 4096 set.  30 17:02 its-client
drwxrwxr-x 7 kvmk8371 kvmk8371 4096 set.  30 17:02 its_client
drwxrwxr-x 2 kvmk8371 kvmk8371 4096 abr.  15 16:21 its_client.egg-info
drwxrwxr-x 2 kvmk8371 kvmk8371 4096 març  23  2022 __pycache__
drwxrwxr-x 6 kvmk8371 kvmk8371 4096 gen.  25  2022 venv
$ ls -l python/its-client/
total 32
-rwxrwxr-x 1 kvmk8371 kvmk8371  742 set.  30 17:02 docker-entrypoint.sh
-rw-rw-r-- 1 kvmk8371 kvmk8371 2356 set.  30 17:02 Dockerfile
drwxrwxr-x 6 kvmk8371 kvmk8371 4096 set.  30 17:02 its_client
-rw-rw-r-- 1 kvmk8371 kvmk8371 1418 set.  30 17:02 Readme.md
-rwxrwxr-x 1 kvmk8371 kvmk8371   83 set.  30 17:02 requirements.txt
-rw-rw-r-- 1 kvmk8371 kvmk8371  672 set.  30 17:02 setup.cfg
-rw-rw-r-- 1 kvmk8371 kvmk8371 2317 set.  30 17:02 setup.py
-rw-rw-r-- 1 kvmk8371 kvmk8371  843 set.  30 17:02 tox.ini
$ 
 ```

I've got 2 'its-client' and one 'its_client' directories: I don't well understand the new architecture tree :(

**Comment by ymorin-orange** [comment]
> Hum, somthing is strange :
> [...]
> I've got 2 'its-client' and one 'its_client' directories: I don't well understand the new architecture tree :(

I don't understand your issue, because, as you can see by [browsing the files in Github](https://github.com/ymorin-orange/its-client/tree/yem/dir-shuffle/python/), there is only one sub-directory:
image

Did you by chance forgot to run `git clean`, or do you have some untracked/uncomitted files?

**Comment by tigroo** [comment]
> > Hum, somthing is strange :
> > [...]
> > I've got 2 'its-client' and one 'its_client' directories: I don't well understand the new architecture tree :(
> 
> I don't understand your issue, because, as you can see by [browsing the files in Github](https://github.com/ymorin-orange/its-client/tree/yem/dir-shuffle/python/), there is only one sub-directory: image
> 
> Did you by chance forgot to run `git clean`, or do you have some untracked/uncomitted files?

You can see it directly into github : https://github.com/Orange-OpenSource/its-client/pull/41/files

Y'ouve got its-client and its_client at the same time

**Comment by ymorin-orange** [comment]
I still do not understand your issue. The github link you provided does actually show that all the content of the `python/` directory is moved one level deeper into a subdirectory `python/its-client`.

```sh
$ git clone https://github.com/ymorin-orange/its-client
$ cd its-client
$ git checkout origin/yem/dir-shuffle
$ ls -lF python/
total 4
drwxrwxr-x 3 nyma7486 nyma7486 4096 Oct  4 14:45 its-client/
$ ls -lF python/its-client/
total 32
-rwxrwxr-x 1 nyma7486 nyma7486  742 Oct  4 14:45 docker-entrypoint.sh*
-rw-rw-r-- 1 nyma7486 nyma7486 2356 Oct  4 14:45 Dockerfile
drwxrwxr-x 6 nyma7486 nyma7486 4096 Oct  4 14:45 its_client/
-rw-rw-r-- 1 nyma7486 nyma7486 1418 Oct  4 14:45 Readme.md
-rwxrwxr-x 1 nyma7486 nyma7486   83 Oct  4 14:45 requirements.txt*
-rw-rw-r-- 1 nyma7486 nyma7486  672 Oct  4 14:45 setup.cfg
-rw-rw-r-- 1 nyma7486 nyma7486 2317 Oct  4 14:45 setup.py
-rw-rw-r-- 1 nyma7486 nyma7486  843 Oct  4 14:45 tox.ini
```

Maybe that will be clearer what the goal is, if you look at the next branch to come afterwards:
https://github.com/ymorin-orange/its-client/tree/yem/status-client/python

```
$ git checkout origin/yem/status-client
$ ls -lF python/
total 8
drwxrwxr-x 3 nyma7486 nyma7486 4096 Oct  4 14:45 its-client/
drwxrwxr-x 3 nyma7486 nyma7486 4096 Oct  4 14:50 its-status/
```

Or I really missed something... :-/

**Review by tigroo — APPROVED** [review]
Let's go!

**Pull request merged**
