### PR TITLE
rust: add Cargo.lock

### PR DESCRIPTION
**Pull request by ymorin-orange**
A Cargo.lock is required for executables. Without a Cargo.lock, the
build is not reproducible.

Amend the ignore patterns to the rust libs only.

### CODE REVIEW

**Comment by tigroo** [comment]
I don't see immediately what's the token problem. To analyse so...

**Comment by ymorin-orange** [comment]
> I don't see immediately what's the token problem. To analyse so...

Fixed by #7

**Comment by ymorin-orange** [comment]
I will rebase on `master` now that #7 has been merged, just to be sure nothing else broke...

**Review by tigroo — APPROVED** [review]
Ok for me. Be careful @nbuffon : locally, the lock will block own Cargo evolution (remove the old, generate the new and commit it each time we modify the dependencies so...).

**Comment by ymorin-orange** [comment]
> Ok for me. Be careful @nbuffon : locally, the lock will block own Cargo evolution (remove the old, generate the new and commit it each time we modify the dependencies so...).

Generating the lockfile is easy: `cargo generate-lockfile --manifest-path rust/its-client/Cargo.toml`

**Pull request merged**
